---
- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Render nftables.conf
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0600"
  notify: Apply nftables rules

- name: Enable nftables service
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
    daemon_reload: true
